name: lint

on:
  push:
    branches: [ 'main', 'invision-main', 'releases/**' ]
  pull_request:
    branches: [ 'main', 'invision-main', 'releases/**' ]

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.52.2
